### ISSUE TITLE
Multijob issue.

### ISSUE THREAD

**Issue by AussieTrucker87** [Project-Sloth/.github#3]
Hi this ticket is for Futte we spoke on discord about the multijob script having an issue with a police dispatch script on my server. 

Basically when the dispatch script runs PS multijob stops working completely, i believe the check job part is conflicting within both scripts.
I spoke to the creators of the police dispatch script and they had a look on their end and tried some things which did not work.

They sent me a screenshot which is below of some of the code with a message saying to ask you guys if its possible how to replace the functions to make it compatible.

![image](https://github.com/Project-Sloth/.github/assets/134513178/68174c3c-f7a8-4997-8ced-f703a4055fa2)

Below are a few errors I was getting with their dispatch script and also referencing PS multijob, I am not sure if that will help you at all.

![image](https://github.com/Project-Sloth/.github/assets/134513178/8ea84046-f74e-414a-9888-cc9609240567)

![image](https://github.com/Project-Sloth/.github/assets/134513178/448395ed-c212-46bf-be89-5a1dfeed6684)

**Comment by xFutte** [comment]
This is not on our end. They need to provide support for it.

@MonkeyWhisper, can you close this?
